spring:
  cloud:
    profiles:
      active: prod

## Activar un perfil desde la línea de comandos
# =============================================
# File mvn
# --------
# mvn spring-boot:run -Dspring-boot.run.profiles=prod -Dserver.port=9010
# mvn spring-boot:run -Dspring-boot.run.profiles=dev -Dserver.port=9010

# File java
# ---------
# java -jar msv-customer-1.0.0.jar --spring.profiles.active=dev
# java -jar msv-customer-1.0.0.jar --spring.profiles.active=prod

#######################################################################################################################

## Activar un perfil en tu IDE
# ============================
# Si estás usando un IDE como IntelliJ IDEA o Eclipse, puedes establecer el perfil en la configuración de ejecución:

# IntelliJ IDEA
# ================
# Ve a Run > Edit Configurations y en la pestaña de configuraciones del proyecto añade :
# --spring.profiles.active=dev
# --spring.profiles.active=prod
# en el campo de "Program Arguments".

# Eclipse
# ==========
# Ve a Run > Run Configurations, selecciona tu proyecto, y en la pestaña Arguments añade:
# --spring.profiles.active=dev
# --spring.profiles.active=prod
# en "Program Arguments".